type IconName = "vertex" | "bell" | "search" | "play" | "file" | "bookmark" | "chart" | "clock" | "user" | "chevron" | "chevron-left" | "external" | "eye" | "grid" | "target" | "accessibility" | "star";
export function Icon({ name, filled = false }: { name: IconName; filled?: boolean }) {
  const common = { width: 20, height: 20, viewBox: "0 0 24 24", fill: filled ? "currentColor" : "none", stroke: "currentColor", strokeWidth: 1.7, strokeLinecap: "round" as const, strokeLinejoin: "round" as const, "aria-hidden": true };
  const paths: Record<IconName, React.ReactNode> = {
    vertex: <path fill="currentColor" stroke="none" d="M2 3h20l-10 18L2 3Zm5.7 3.4 4.3 7.9 4.3-7.9H7.7Z" />, bell: <><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9" /><path d="M10 21h4" /></>, search: <><circle cx="10.8" cy="10.8" r="6.5" /><path d="m16 16 4.5 4.5" /></>, play: <><circle cx="12" cy="12" r="8.5" /><path fill="currentColor" stroke="none" d="m10 8.5 5.5 3.5-5.5 3.5V8.5Z" /></>, file: <><path d="M6 3h8l4 4v14H6z" /><path d="M14 3v5h4M9 13h6M9 17h6" /></>, bookmark: <path d="M6 4.5A1.5 1.5 0 0 1 7.5 3h9A1.5 1.5 0 0 1 18 4.5V21l-6-3-6 3V4.5Z" />, chart: <><path d="M5 20v-5M10 20V9M15 20V4M20 20v-8" /><path d="M3 20h19" /></>, clock: <><circle cx="12" cy="12" r="8.5" /><path d="M12 7v5l3 2" /></>, user: <><circle cx="12" cy="8" r="3" /><path d="M5 20a7 7 0 0 1 14 0" /></>, chevron: <path d="m9 5 7 7-7 7" />, "chevron-left": <path d="m15 5-7 7 7 7" />, external: <><path d="M14 5h5v5M19 5l-8 8" /><path d="M19 13v5a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1h5" /></>, eye: <><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z" /><circle cx="12" cy="12" r="2.5" /></>, grid: <><rect x="3" y="3" width="7" height="7" rx="1" /><rect x="14" y="3" width="7" height="7" rx="1" /><rect x="3" y="14" width="7" height="7" rx="1" /><rect x="14" y="14" width="7" height="7" rx="1" /></>, target: <><circle cx="12" cy="12" r="8.5" /><circle cx="12" cy="12" r="4.5" /><circle cx="12" cy="12" r="1" fill="currentColor" /></>, accessibility: <><circle cx="12" cy="4.5" r="1.5" /><path d="M5 8h14M12 8v12M8 20l4-7 4 7" /></>, star: <path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-2.9-5.6 2.9 1.1-6.2L3 9.6l6.2-.9L12 3Z" />,
  };
  return <svg {...common}>{paths[name]}</svg>;
}
export function Panel({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`panel ${className}`}>{children}</section>; }
export function SectionHeading({ number, title }: { number: string; title: string }) { return <div className="section-heading"><b>{number}</b><span>{title}</span></div>; }
export function Button({ children, variant = "primary", disabled = false }: { children: React.ReactNode; variant?: "primary" | "secondary" | "tertiary" | "text"; disabled?: boolean }) { return <button type="button" className={`button button-${variant}`} disabled={disabled}>{children}</button>; }
export function Badge({ children, tone }: { children: React.ReactNode; tone: "video" | "lesson" | "popular" }) { return <span className={`badge badge-${tone}`}>{children}</span>; }
export function Status({ label, tone }: { label: string; tone: "progress" | "complete" | "playing" | "locked" }) { return <span className={`status status-${tone}`}><i>{tone === "complete" ? "✓" : tone === "locked" ? "♙" : tone === "playing" ? "▶" : ""}</i>{label}</span>; }
export function Card({ type }: { type: "course" | "video" | "lesson" | "resource" }) { const data = { course: { badge: "N", title: "Next.js for Production", text: "Build scalable, high-performance web applications with Next.js.", meta: "▥ Intermediate   ◷ 18h 24m   ▫ 12 modules" }, video: { badge: "VIDEO", title: "Data Fetching in Server Components", text: "Learn how to fetch data on the server using async/await and Next.js best practices.", meta: "Lesson 5.1   ·   12:45" }, lesson: { badge: "LESSON", title: "Data Fetching & Caching", text: "Explore different data fetching methods in Next.js and how to cache and revalidate data for optimal performance.", meta: "Module 5" }, resource: { badge: "▤", title: "Caching and Revalidation Guide", text: "Deep dive into Next.js caching strategies.", meta: "PDF   ·   1.2 MB" } }[type]; return <article className={`design-card card-${type}`}><div className="card-top"><span className="card-icon">{data.badge}</span>{type !== "course" && type !== "resource" && <Badge tone={type === "video" ? "video" : "lesson"}>{type === "video" ? "VIDEO" : "LESSON"}</Badge>}</div><h3>{data.title}</h3><p>{data.text}</p><small>{data.meta}</small>{type === "video" && <a>◉ Watch from 12:45</a>}{type === "lesson" && <a>View lesson <Icon name="external" /></a>}{type === "resource" && <a><Icon name="external" /></a>}</article>; }
